# Generated by Django 4.0 on 2022-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Edition', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
